export interface CheatSheetItem {
  syntax: string;
  description: string;
}

export interface CheatSheetSection {
  title: string;
  items: CheatSheetItem[];
}

export interface CheatSheet {
  slug: string;
  title: string;
  description: string;
  icon: string;
  seoTitle: string;
  seoDescription: string;
  sections: CheatSheetSection[];
}

export const cheatsheets: CheatSheet[] = [
  {
    slug: "git",
    title: "Git Commands",
    description: "Essential Git commands for daily development workflow",
    icon: "🔀",
    seoTitle: "Git Cheat Sheet — All Git Commands in One Page",
    seoDescription: "Complete Git commands cheat sheet: clone, commit, push, pull, branch, merge, rebase, stash, log, and more. Copy any command with one click.",
    sections: [
      {
        title: "Setup & Config",
        items: [
          { syntax: "git config --global user.name \"[name]\"", description: "Set author name" },
          { syntax: "git config --global user.email \"[email]\"", description: "Set author email" },
          { syntax: "git config --global core.editor [editor]", description: "Set default editor" },
          { syntax: "git config --list", description: "List all config settings" },
          { syntax: "git init", description: "Initialize a new repository" },
          { syntax: "git clone [url]", description: "Clone a remote repository" },
        ],
      },
      {
        title: "Stage & Commit",
        items: [
          { syntax: "git status", description: "Show working tree status" },
          { syntax: "git add [file]", description: "Stage a specific file" },
          { syntax: "git add .", description: "Stage all changes" },
          { syntax: "git add -p", description: "Stage changes interactively (hunks)" },
          { syntax: "git commit -m \"[message]\"", description: "Commit staged changes" },
          { syntax: "git commit -am \"[message]\"", description: "Stage tracked files & commit" },
          { syntax: "git commit --amend", description: "Amend the last commit" },
          { syntax: "git reset [file]", description: "Unstage a file" },
          { syntax: "git reset --soft HEAD~1", description: "Undo last commit, keep changes staged" },
          { syntax: "git reset --hard HEAD~1", description: "Undo last commit, discard changes" },
          { syntax: "git stash", description: "Stash working directory changes" },
          { syntax: "git stash pop", description: "Restore stashed changes" },
          { syntax: "git stash list", description: "List all stashes" },
        ],
      },
      {
        title: "Branch & Merge",
        items: [
          { syntax: "git branch", description: "List local branches" },
          { syntax: "git branch -a", description: "List all branches (local + remote)" },
          { syntax: "git branch [name]", description: "Create a new branch" },
          { syntax: "git branch -d [name]", description: "Delete a branch" },
          { syntax: "git switch [name]", description: "Switch to a branch" },
          { syntax: "git switch -c [name]", description: "Create and switch to a new branch" },
          { syntax: "git checkout [name]", description: "Switch to a branch (legacy)" },
          { syntax: "git checkout -b [name]", description: "Create & switch (legacy)" },
          { syntax: "git merge [branch]", description: "Merge branch into current branch" },
          { syntax: "git merge --squash [branch]", description: "Squash merge a branch" },
          { syntax: "git rebase [branch]", description: "Rebase current branch onto another" },
          { syntax: "git rebase -i HEAD~[n]", description: "Interactive rebase last n commits" },
          { syntax: "git cherry-pick [commit]", description: "Apply a specific commit to current branch" },
        ],
      },
      {
        title: "Remote & Push",
        items: [
          { syntax: "git remote -v", description: "List remote repositories" },
          { syntax: "git remote add [name] [url]", description: "Add a remote" },
          { syntax: "git fetch [remote]", description: "Fetch from remote (no merge)" },
          { syntax: "git pull [remote] [branch]", description: "Fetch and merge from remote" },
          { syntax: "git pull --rebase", description: "Pull with rebase instead of merge" },
          { syntax: "git push [remote] [branch]", description: "Push branch to remote" },
          { syntax: "git push -u origin [branch]", description: "Push and set upstream" },
          { syntax: "git push --force-with-lease", description: "Force push (safe version)" },
          { syntax: "git push --tags", description: "Push tags to remote" },
        ],
      },
      {
        title: "Inspect & History",
        items: [
          { syntax: "git log", description: "Show commit history" },
          { syntax: "git log --oneline --graph --all", description: "Compact history graph" },
          { syntax: "git log -p [file]", description: "Show changes for a file over time" },
          { syntax: "git diff", description: "Show unstaged changes" },
          { syntax: "git diff --staged", description: "Show staged changes" },
          { syntax: "git diff [branch1]..[branch2]", description: "Compare two branches" },
          { syntax: "git show [commit]", description: "Show a commit's details" },
          { syntax: "git blame [file]", description: "Show who changed each line" },
          { syntax: "git reflog", description: "Show HEAD change history (recovery!)" },
          { syntax: "git tag [name]", description: "Create a tag" },
          { syntax: "git tag -a [name] -m \"[msg]\"", description: "Create an annotated tag" },
        ],
      },
    ],
  },
  {
    slug: "docker",
    title: "Docker Commands",
    description: "Essential Docker commands for container management",
    icon: "🐳",
    seoTitle: "Docker Cheat Sheet — Docker Commands Quick Reference",
    seoDescription: "Complete Docker cheat sheet: run, build, compose, exec, logs, volumes, networks. Copy any Docker command with one click. Perfect for DevOps and backend developers.",
    sections: [
      {
        title: "Container Lifecycle",
        items: [
          { syntax: "docker run [image]", description: "Create and start a container" },
          { syntax: "docker run -d [image]", description: "Run container in detached mode" },
          { syntax: "docker run -it [image] /bin/bash", description: "Run interactively with shell" },
          { syntax: "docker run -p [host]:[container] [image]", description: "Map host port to container" },
          { syntax: "docker run -v [host]:[container] [image]", description: "Mount a volume" },
          { syntax: "docker run --name [name] [image]", description: "Name a container" },
          { syntax: "docker run --rm [image]", description: "Auto-remove container on exit" },
          { syntax: "docker run -e [KEY]=[VALUE] [image]", description: "Set environment variable" },
          { syntax: "docker start [container]", description: "Start a stopped container" },
          { syntax: "docker stop [container]", description: "Stop a running container" },
          { syntax: "docker restart [container]", description: "Restart a container" },
          { syntax: "docker rm [container]", description: "Remove a container" },
          { syntax: "docker rm -f [container]", description: "Force remove a running container" },
        ],
      },
      {
        title: "Inspect & Debug",
        items: [
          { syntax: "docker ps", description: "List running containers" },
          { syntax: "docker ps -a", description: "List all containers" },
          { syntax: "docker logs [container]", description: "Show container logs" },
          { syntax: "docker logs -f [container]", description: "Follow container logs (tail -f)" },
          { syntax: "docker logs --tail 100 [container]", description: "Show last 100 log lines" },
          { syntax: "docker exec -it [container] /bin/bash", description: "Open shell in running container" },
          { syntax: "docker inspect [container]", description: "Show container details (JSON)" },
          { syntax: "docker stats", description: "Live container resource usage" },
          { syntax: "docker top [container]", description: "Show running processes in container" },
          { syntax: "docker port [container]", description: "Show port mappings" },
        ],
      },
      {
        title: "Images",
        items: [
          { syntax: "docker images", description: "List all images" },
          { syntax: "docker pull [image]", description: "Download an image" },
          { syntax: "docker push [image]", description: "Push image to registry" },
          { syntax: "docker build -t [name] .", description: "Build image from Dockerfile" },
          { syntax: "docker build --no-cache -t [name] .", description: "Build without cache" },
          { syntax: "docker tag [image] [new]", description: "Tag an image" },
          { syntax: "docker rmi [image]", description: "Remove an image" },
          { syntax: "docker image prune", description: "Remove unused images" },
          { syntax: "docker history [image]", description: "Show image layer history" },
          { syntax: "docker save [image] > file.tar", description: "Export image to tar" },
          { syntax: "docker load < file.tar", description: "Import image from tar" },
        ],
      },
      {
        title: "Volumes & Networks",
        items: [
          { syntax: "docker volume ls", description: "List volumes" },
          { syntax: "docker volume create [name]", description: "Create a volume" },
          { syntax: "docker volume rm [name]", description: "Remove a volume" },
          { syntax: "docker volume prune", description: "Remove unused volumes" },
          { syntax: "docker network ls", description: "List networks" },
          { syntax: "docker network create [name]", description: "Create a network" },
          { syntax: "docker network connect [net] [container]", description: "Connect container to network" },
        ],
      },
      {
        title: "Docker Compose",
        items: [
          { syntax: "docker compose up", description: "Start all services" },
          { syntax: "docker compose up -d", description: "Start in detached mode" },
          { syntax: "docker compose up --build", description: "Rebuild images before starting" },
          { syntax: "docker compose down", description: "Stop and remove all services" },
          { syntax: "docker compose down -v", description: "Also remove volumes" },
          { syntax: "docker compose ps", description: "List compose services" },
          { syntax: "docker compose logs -f", description: "Follow all service logs" },
          { syntax: "docker compose exec [service] /bin/bash", description: "Open shell in a service" },
          { syntax: "docker compose restart [service]", description: "Restart a specific service" },
        ],
      },
      {
        title: "Cleanup",
        items: [
          { syntax: "docker system prune", description: "Remove unused data (ask confirm)" },
          { syntax: "docker system prune -af", description: "Remove EVERYTHING unused (no confirm)" },
          { syntax: "docker container prune", description: "Remove stopped containers" },
          { syntax: "docker image prune -a", description: "Remove all unused images" },
        ],
      },
    ],
  },
  {
    slug: "css-flexbox",
    title: "CSS Flexbox",
    description: "Complete Flexbox reference for container and items",
    icon: "📐",
    seoTitle: "CSS Flexbox Cheat Sheet — Complete Flexbox Reference",
    seoDescription: "Complete CSS Flexbox cheat sheet: all container and item properties with visual examples. justify-content, align-items, flex-wrap, gap, and more. One-click copy.",
    sections: [
      {
        title: "Container Properties",
        items: [
          { syntax: "display: flex;", description: "Enable flexbox on container" },
          { syntax: "display: inline-flex;", description: "Inline flex container" },
          { syntax: "flex-direction: row;", description: "Left to right (default)" },
          { syntax: "flex-direction: row-reverse;", description: "Right to left" },
          { syntax: "flex-direction: column;", description: "Top to bottom" },
          { syntax: "flex-direction: column-reverse;", description: "Bottom to top" },
          { syntax: "flex-wrap: nowrap;", description: "Single line (default)" },
          { syntax: "flex-wrap: wrap;", description: "Wrap to multiple lines" },
          { syntax: "flex-wrap: wrap-reverse;", description: "Wrap in reverse" },
          { syntax: "flex-flow: row wrap;", description: "Shorthand for direction + wrap" },
          { syntax: "justify-content: flex-start;", description: "Items at start of main axis" },
          { syntax: "justify-content: flex-end;", description: "Items at end of main axis" },
          { syntax: "justify-content: center;", description: "Items centered on main axis" },
          { syntax: "justify-content: space-between;", description: "Equal space between items" },
          { syntax: "justify-content: space-around;", description: "Equal space around items" },
          { syntax: "justify-content: space-evenly;", description: "Equal space everywhere" },
          { syntax: "align-items: stretch;", description: "Fill cross axis (default)" },
          { syntax: "align-items: flex-start;", description: "Items at start of cross axis" },
          { syntax: "align-items: flex-end;", description: "Items at end of cross axis" },
          { syntax: "align-items: center;", description: "Items centered on cross axis" },
          { syntax: "align-items: baseline;", description: "Items aligned by text baseline" },
          { syntax: "align-content: stretch;", description: "Lines stretch (default)" },
          { syntax: "align-content: center;", description: "Lines centered" },
          { syntax: "align-content: space-between;", description: "Lines with equal space" },
          { syntax: "gap: 16px;", description: "Gap between all items" },
          { syntax: "row-gap: 10px; column-gap: 20px;", description: "Separate row and column gaps" },
        ],
      },
      {
        title: "Item Properties",
        items: [
          { syntax: "order: 1;", description: "Change visual order (default 0)" },
          { syntax: "flex-grow: 1;", description: "Grow to fill available space" },
          { syntax: "flex-shrink: 0;", description: "Prevent shrinking" },
          { syntax: "flex-basis: 200px;", description: "Initial size before grow/shrink" },
          { syntax: "flex: 1;", description: "Shorthand: grow=1, shrink=1, basis=0" },
          { syntax: "flex: 0 0 300px;", description: "Fixed width/height of 300px" },
          { syntax: "align-self: auto;", description: "Inherit container align-items" },
          { syntax: "align-self: flex-start;", description: "Override to start" },
          { syntax: "align-self: flex-end;", description: "Override to end" },
          { syntax: "align-self: center;", description: "Override to center" },
          { syntax: "align-self: stretch;", description: "Override to stretch" },
        ],
      },
    ],
  },
  {
    slug: "css-grid",
    title: "CSS Grid",
    description: "Complete CSS Grid Layout reference",
    icon: "📏",
    seoTitle: "CSS Grid Cheat Sheet — Complete Grid Layout Reference",
    seoDescription: "Complete CSS Grid cheat sheet: grid-template-columns, grid-area, fr units, minmax, auto-fit, and all grid properties. One-click copy for frontend developers.",
    sections: [
      {
        title: "Container Properties",
        items: [
          { syntax: "display: grid;", description: "Enable grid layout" },
          { syntax: "display: inline-grid;", description: "Inline grid container" },
          { syntax: "grid-template-columns: 1fr 1fr 1fr;", description: "Three equal columns" },
          { syntax: "grid-template-columns: repeat(3, 1fr);", description: "Same as above (repeat)" },
          { syntax: "grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));", description: "Responsive auto-fit grid" },
          { syntax: "grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));", description: "Auto-fill (keeps empty tracks)" },
          { syntax: "grid-template-columns: 200px 1fr 200px;", description: "Fixed sidebar + fluid center" },
          { syntax: "grid-template-rows: 100px auto 100px;", description: "Header, fluid content, footer" },
          { syntax: "grid-template-rows: minmax(100px, auto);", description: "Minimum 100px, grows if needed" },
          { syntax: "column-gap: 20px; row-gap: 20px;", description: "Gap between columns and rows" },
          { syntax: "gap: 16px;", description: "Shorthand for row-gap + column-gap" },
          { syntax: "grid-template-areas: 'header header' 'sidebar main' 'footer footer';", description: "Named grid areas layout" },
          { syntax: "justify-items: center;", description: "Align items horizontally in their cell" },
          { syntax: "align-items: center;", description: "Align items vertically in their cell" },
          { syntax: "place-items: center;", description: "Shorthand for align + justify items" },
          { syntax: "justify-content: center;", description: "Align whole grid horizontally" },
          { syntax: "align-content: center;", description: "Align whole grid vertically" },
        ],
      },
      {
        title: "Item Properties",
        items: [
          { syntax: "grid-column: 1 / 3;", description: "Span from column line 1 to 3" },
          { syntax: "grid-column: span 2;", description: "Span 2 columns" },
          { syntax: "grid-column: 1 / -1;", description: "Span full width" },
          { syntax: "grid-row: 2 / 4;", description: "Span from row line 2 to 4" },
          { syntax: "grid-area: header;", description: "Place in named area" },
          { syntax: "grid-area: 1 / 1 / 3 / 3;", description: "Shorthand: row-start / col-start / row-end / col-end" },
          { syntax: "justify-self: center;", description: "Align self horizontally" },
          { syntax: "align-self: center;", description: "Align self vertically" },
          { syntax: "place-self: center;", description: "Shorthand for align + justify self" },
        ],
      },
    ],
  },
  {
    slug: "react-hooks",
    title: "React Hooks",
    description: "All React hooks with usage examples",
    icon: "⚛️",
    seoTitle: "React Hooks Cheat Sheet — Complete Hooks Reference with Examples",
    seoDescription: "Complete React hooks cheat sheet: useState, useEffect, useContext, useRef, useMemo, useCallback, useReducer, and custom hooks. Copy code examples with one click.",
    sections: [
      {
        title: "Basic Hooks",
        items: [
          { syntax: "const [state, setState] = useState(initialValue);", description: "Add state to a functional component" },
          { syntax: "const [count, setCount] = useState(0);", description: "Number state example" },
          { syntax: "const [user, setUser] = useState(null);", description: "Object state (null initial)" },
          { syntax: "setState(prev => prev + 1);", description: "Update based on previous state" },
          { syntax: "useEffect(() => { /* side effect */ }, []);", description: "Run once on mount (empty deps)" },
          { syntax: "useEffect(() => { /* side effect */ }, [dep]);", description: "Run when dep changes" },
          { syntax: "useEffect(() => { return () => { /* cleanup */ }; }, []);", description: "With cleanup function" },
          { syntax: "const ctx = useContext(MyContext);", description: "Subscribe to context value" },
        ],
      },
      {
        title: "Refs",
        items: [
          { syntax: "const ref = useRef(initialValue);", description: "Create a mutable ref object" },
          { syntax: "const inputRef = useRef(null);", description: "DOM element ref" },
          { syntax: "inputRef.current?.focus();", description: "Focus an input via ref" },
          { syntax: "const prev = useRef(value); useEffect(() => { prev.current = value; });", description: "Track previous value" },
        ],
      },
      {
        title: "Performance Hooks",
        items: [
          { syntax: "const memoized = useMemo(() => compute(a, b), [a, b]);", description: "Memoize expensive computation" },
          { syntax: "const handleClick = useCallback(() => { doThing(a); }, [a]);", description: "Memoize callback function" },
          { syntax: "const items = useMemo(() => list.filter(Boolean), [list]);", description: "Memoize derived data" },
          { syntax: "React.memo(Component)", description: "Memoize component (skip re-render if props same)" },
          { syntax: "<Component child={<Static />} />", description: "Pass JSX as prop (avoids re-render)" },
        ],
      },
      {
        title: "Advanced Hooks",
        items: [
          { syntax: "const [state, dispatch] = useReducer(reducer, initialState);", description: "Complex state with reducer pattern" },
          { syntax: "useReducer(reducer, initialState, initFn);", description: "With lazy initialization" },
          { syntax: "const id = useId();", description: "Generate unique ID (for a11y)" },
          { syntax: "useDeferredValue(value)", description: "Defer update of slow state" },
          { syntax: "useTransition() → [isPending, startTransition]", description: "Mark update as non-urgent" },
        ],
      },
      {
        title: "Custom Hook Patterns",
        items: [
          { syntax: "function useToggle(initial = false) {\n  const [on, setOn] = useState(initial);\n  return [on, () => setOn(p => !p)];\n}", description: "Toggle boolean hook" },
          { syntax: "function useDebounce(value, delay = 300) {\n  const [debounced, setDebounced] = useState(value);\n  useEffect(() => {\n    const t = setTimeout(() => setDebounced(value), delay);\n    return () => clearTimeout(t);\n  }, [value, delay]);\n  return debounced;\n}", description: "Debounce a value" },
          { syntax: "function useLocalStorage(key, initial) {\n  const [val, setVal] = useState(() => {\n    try { return JSON.parse(localStorage.getItem(key)) ?? initial; }\n    catch { return initial; }\n  });\n  useEffect(() => localStorage.setItem(key, JSON.stringify(val)), [key, val]);\n  return [val, setVal];\n}", description: "Persist state to localStorage" },
          { syntax: "function useFetch(url) {\n  const [data, setData] = useState(null);\n  useEffect(() => { fetch(url).then(r => r.json()).then(setData); }, [url]);\n  return data;\n}", description: "Simple data fetching hook" },
        ],
      },
    ],
  },
  {
    slug: "js-array",
    title: "JavaScript Array Methods",
    description: "All JavaScript array methods with examples",
    icon: "📚",
    seoTitle: "JavaScript Array Methods Cheat Sheet — Complete JS Array Reference",
    seoDescription: "Complete JavaScript array methods cheat sheet: map, filter, reduce, find, sort, slice, splice, and all ES6+ array methods. Copy code examples instantly.",
    sections: [
      {
        title: "Transform",
        items: [
          { syntax: "arr.map(x => x * 2)", description: "Create new array by transforming each element" },
          { syntax: "arr.filter(x => x > 0)", description: "Create new array with elements that pass test" },
          { syntax: "arr.reduce((sum, x) => sum + x, 0)", description: "Reduce array to single value" },
          { syntax: "arr.reduce((acc, x) => { acc[x.id] = x; return acc; }, {})", description: "Convert array to object (index by key)" },
          { syntax: "arr.flatMap(x => [x, x * 2])", description: "map then flatten one level" },
          { syntax: "arr.flat(2)", description: "Flatten nested arrays (depth 2)" },
          { syntax: "arr.flat(Infinity)", description: "Flatten all nesting levels" },
        ],
      },
      {
        title: "Search & Test",
        items: [
          { syntax: "arr.find(x => x.id === 5)", description: "Find first matching element" },
          { syntax: "arr.findIndex(x => x.id === 5)", description: "Find index of first match" },
          { syntax: "arr.findLast(x => x > 10)", description: "Find last matching element" },
          { syntax: "arr.includes(value)", description: "Check if array contains value" },
          { syntax: "arr.indexOf(value)", description: "Find index of value (-1 if not found)" },
          { syntax: "arr.some(x => x > 0)", description: "Check if ANY element passes test" },
          { syntax: "arr.every(x => x > 0)", description: "Check if ALL elements pass test" },
        ],
      },
      {
        title: "Add / Remove / Reorder",
        items: [
          { syntax: "arr.push(item)", description: "Add to end (mutates)" },
          { syntax: "arr.pop()", description: "Remove from end (mutates)" },
          { syntax: "arr.unshift(item)", description: "Add to beginning (mutates)" },
          { syntax: "arr.shift()", description: "Remove from beginning (mutates)" },
          { syntax: "arr.splice(start, deleteCount, ...items)", description: "Remove/replace items (mutates)" },
          { syntax: "arr.slice(start, end)", description: "Copy portion of array (immutable)" },
          { syntax: "arr.sort((a, b) => a - b)", description: "Sort numbers ascending" },
          { syntax: "arr.sort((a, b) => a.localeCompare(b))", description: "Sort strings" },
          { syntax: "arr.reverse()", description: "Reverse order (mutates)" },
          { syntax: "arr.toReversed()", description: "New reversed array (immutable, ES2023)" },
          { syntax: "arr.toSorted((a, b) => a - b)", description: "New sorted array (immutable, ES2023)" },
          { syntax: "arr.with(index, newValue)", description: "Replace at index (immutable, ES2023)" },
        ],
      },
      {
        title: "Utility",
        items: [
          { syntax: "arr.length", description: "Get array length" },
          { syntax: "Array.isArray(arr)", description: "Check if value is an array" },
          { syntax: "arr.join(', ')", description: "Join elements into string" },
          { syntax: "arr.concat(arr2)", description: "Merge arrays (immutable)" },
          { syntax: "[...arr1, ...arr2]", description: "Merge with spread (modern)" },
          { syntax: "Array.from(iterable)", description: "Create array from iterable" },
          { syntax: "Array.from({ length: 5 }, (_, i) => i)", description: "Create array [0, 1, 2, 3, 4]" },
          { syntax: "Array(5).fill(0)", description: "Create array of 5 zeros" },
          { syntax: "new Set(arr)", description: "Remove duplicates" },
        ],
      },
    ],
  },
  {
    slug: "linux",
    title: "Linux Commands",
    description: "Essential Linux terminal commands for developers",
    icon: "🐧",
    seoTitle: "Linux Commands Cheat Sheet — Terminal Commands Quick Reference",
    seoDescription: "Complete Linux commands cheat sheet: file ops, permissions, process management, networking, grep, find, sed, awk, and more. Copy any command with one click.",
    sections: [
      {
        title: "File Operations",
        items: [
          { syntax: "ls -la", description: "List all files with details" },
          { syntax: "ls -lh", description: "List with human-readable sizes" },
          { syntax: "cd /path/to/dir", description: "Change directory" },
          { syntax: "pwd", description: "Print working directory" },
          { syntax: "mkdir -p path/to/dir", description: "Create directory (with parents)" },
          { syntax: "rm file", description: "Remove file" },
          { syntax: "rm -rf dir", description: "Remove directory recursively (careful!)" },
          { syntax: "cp source dest", description: "Copy file" },
          { syntax: "cp -r source dest", description: "Copy directory recursively" },
          { syntax: "mv source dest", description: "Move or rename file" },
          { syntax: "ln -s target link", description: "Create symbolic link" },
          { syntax: "touch file", description: "Create empty file or update timestamp" },
        ],
      },
      {
        title: "View & Edit",
        items: [
          { syntax: "cat file", description: "Print file contents" },
          { syntax: "less file", description: "View file with pagination" },
          { syntax: "head -n 20 file", description: "Show first 20 lines" },
          { syntax: "tail -n 20 file", description: "Show last 20 lines" },
          { syntax: "tail -f file", description: "Follow file updates (live log)" },
          { syntax: "wc -l file", description: "Count lines" },
          { syntax: "wc -c file", description: "Count bytes" },
          { syntax: "sort file", description: "Sort lines alphabetically" },
          { syntax: "sort -n file", description: "Sort numerically" },
          { syntax: "uniq file", description: "Remove duplicate adjacent lines" },
          { syntax: "sort file | uniq -c", description: "Count occurrences of each line" },
        ],
      },
      {
        title: "Permissions",
        items: [
          { syntax: "chmod 755 file", description: "rwxr-xr-x (owner all, group/other read+exec)" },
          { syntax: "chmod 644 file", description: "rw-r--r-- (owner rw, other read-only)" },
          { syntax: "chmod 600 file", description: "rw------- (owner rw, no one else)" },
          { syntax: "chmod +x script.sh", description: "Make file executable" },
          { syntax: "chown user:group file", description: "Change file owner and group" },
          { syntax: "chown -R user:group dir/", description: "Recursively change ownership" },
        ],
      },
      {
        title: "Processes",
        items: [
          { syntax: "ps aux", description: "List all running processes" },
          { syntax: "ps aux | grep [name]", description: "Find process by name" },
          { syntax: "top", description: "Interactive process monitor" },
          { syntax: "htop", description: "Better interactive process monitor" },
          { syntax: "kill [PID]", description: "Terminate process by PID" },
          { syntax: "kill -9 [PID]", description: "Force kill process" },
          { syntax: "pkill [name]", description: "Kill process by name" },
          { syntax: "killall [name]", description: "Kill all processes by name" },
          { syntax: "bg", description: "Resume suspended job in background" },
          { syntax: "fg", description: "Bring background job to foreground" },
          { syntax: "nohup command &", description: "Run command immune to hangups" },
        ],
      },
      {
        title: "Search & Find",
        items: [
          { syntax: "grep 'pattern' file", description: "Search for pattern in file" },
          { syntax: "grep -r 'pattern' dir/", description: "Search recursively" },
          { syntax: "grep -i 'pattern' file", description: "Case-insensitive search" },
          { syntax: "grep -v 'pattern' file", description: "Invert match (exclude)" },
          { syntax: "grep -n 'pattern' file", description: "Show line numbers" },
          { syntax: "grep -c 'pattern' file", description: "Count matches" },
          { syntax: "grep -A 3 -B 2 'pattern' file", description: "Show 3 lines after and 2 before match" },
          { syntax: "find dir/ -name '*.js'", description: "Find files by name pattern" },
          { syntax: "find dir/ -type f -size +10M", description: "Find files larger than 10MB" },
          { syntax: "find dir/ -mtime -7", description: "Find files modified in last 7 days" },
          { syntax: "find dir/ -name '*.log' -delete", description: "Find and delete log files" },
          { syntax: "find dir/ -name '*.js' -exec grep 'TODO' {} +", description: "Find .js files containing TODO" },
        ],
      },
      {
        title: "Disk & Network",
        items: [
          { syntax: "df -h", description: "Show disk usage (human-readable)" },
          { syntax: "du -sh dir/", description: "Show directory size" },
          { syntax: "du -sh * | sort -h", description: "Sort items by size" },
          { syntax: "free -h", description: "Show memory usage" },
          { syntax: "curl -X GET https://api.example.com", description: "Make HTTP GET request" },
          { syntax: "curl -X POST -d '{}' https://api.example.com", description: "Make HTTP POST request" },
          { syntax: "wget https://example.com/file.tar.gz", description: "Download a file" },
          { syntax: "tar -czf archive.tar.gz dir/", description: "Create tar.gz archive" },
          { syntax: "tar -xzf archive.tar.gz", description: "Extract tar.gz archive" },
          { syntax: "netstat -tlnp", description: "Show listening ports" },
          { syntax: "ss -tlnp", description: "Show listening ports (modern)" },
        ],
      },
    ],
  },
  {
    slug: "sql",
    title: "SQL Basics",
    description: "Essential SQL queries for everyday database work",
    icon: "🗄️",
    seoTitle: "SQL Cheat Sheet — Essential SQL Queries Quick Reference",
    seoDescription: "Complete SQL cheat sheet: SELECT, JOIN, GROUP BY, subqueries, indexes, transactions, and window functions. Copy any SQL query with one click.",
    sections: [
      {
        title: "SELECT & Filter",
        items: [
          { syntax: "SELECT * FROM users;", description: "Select all columns" },
          { syntax: "SELECT id, name, email FROM users;", description: "Select specific columns" },
          { syntax: "SELECT DISTINCT country FROM users;", description: "Select unique values" },
          { syntax: "SELECT * FROM users WHERE age >= 18;", description: "Filter with condition" },
          { syntax: "SELECT * FROM users WHERE name LIKE 'J%';", description: "Pattern match (% = any chars)" },
          { syntax: "SELECT * FROM users WHERE id IN (1, 2, 3);", description: "Match any in list" },
          { syntax: "SELECT * FROM users WHERE age BETWEEN 18 AND 65;", description: "Range filter (inclusive)" },
          { syntax: "SELECT * FROM users WHERE email IS NULL;", description: "Check for NULL" },
          { syntax: "SELECT * FROM users WHERE age > 18 AND city = 'NYC';", description: "Multiple conditions (AND)" },
          { syntax: "SELECT * FROM users WHERE role = 'admin' OR role = 'mod';", description: "Multiple conditions (OR)" },
        ],
      },
      {
        title: "Sort & Limit",
        items: [
          { syntax: "SELECT * FROM users ORDER BY name ASC;", description: "Sort ascending" },
          { syntax: "SELECT * FROM users ORDER BY created_at DESC;", description: "Sort descending (newest first)" },
          { syntax: "SELECT * FROM users ORDER BY age DESC, name ASC;", description: "Sort by multiple columns" },
          { syntax: "SELECT * FROM users LIMIT 10;", description: "Limit rows returned" },
          { syntax: "SELECT * FROM users LIMIT 10 OFFSET 20;", description: "Pagination: skip 20, take 10" },
        ],
      },
      {
        title: "Aggregate & GROUP BY",
        items: [
          { syntax: "SELECT COUNT(*) FROM users;", description: "Count all rows" },
          { syntax: "SELECT AVG(age) FROM users;", description: "Average value" },
          { syntax: "SELECT SUM(salary) FROM employees;", description: "Sum values" },
          { syntax: "SELECT MAX(price), MIN(price) FROM products;", description: "Max and min values" },
          { syntax: "SELECT city, COUNT(*) FROM users GROUP BY city;", description: "Count by group" },
          { syntax: "SELECT city, COUNT(*) AS n FROM users GROUP BY city HAVING n > 5;", description: "Filter groups (HAVING)" },
        ],
      },
      {
        title: "JOIN",
        items: [
          { syntax: "SELECT * FROM orders JOIN users ON orders.user_id = users.id;", description: "INNER JOIN: matching rows only" },
          { syntax: "SELECT * FROM users LEFT JOIN orders ON users.id = orders.user_id;", description: "LEFT JOIN: all users + matching orders" },
          { syntax: "SELECT * FROM users RIGHT JOIN orders ON users.id = orders.user_id;", description: "RIGHT JOIN: all orders + matching users" },
          { syntax: "SELECT * FROM users FULL OUTER JOIN orders ON users.id = orders.user_id;", description: "FULL JOIN: everything from both" },
          { syntax: "SELECT u.name, o.total FROM users u JOIN orders o ON u.id = o.user_id;", description: "JOIN with table aliases" },
        ],
      },
      {
        title: "Modify Data",
        items: [
          { syntax: "INSERT INTO users (name, email) VALUES ('Alice', 'a@b.com');", description: "Insert a single row" },
          { syntax: "INSERT INTO users (name, email) VALUES ('A', 'a@b.com'), ('B', 'b@c.com');", description: "Insert multiple rows" },
          { syntax: "UPDATE users SET email = 'new@b.com' WHERE id = 1;", description: "Update specific rows" },
          { syntax: "DELETE FROM users WHERE id = 1;", description: "Delete specific rows" },
          { syntax: "TRUNCATE TABLE users;", description: "Delete all rows (fast, resets auto-increment)" },
        ],
      },
      {
        title: "Schema & Indexes",
        items: [
          { syntax: "CREATE TABLE users (\n  id SERIAL PRIMARY KEY,\n  name VARCHAR(100) NOT NULL,\n  email VARCHAR(255) UNIQUE,\n  created_at TIMESTAMP DEFAULT NOW()\n);", description: "Create table with constraints" },
          { syntax: "ALTER TABLE users ADD COLUMN age INT;", description: "Add a column" },
          { syntax: "ALTER TABLE users DROP COLUMN age;", description: "Drop a column" },
          { syntax: "CREATE INDEX idx_users_email ON users(email);", description: "Create an index" },
          { syntax: "CREATE INDEX idx_users_name_email ON users(name, email);", description: "Create composite index" },
          { syntax: "DROP INDEX idx_users_email;", description: "Drop an index" },
        ],
      },
      {
        title: "Window Functions",
        items: [
          { syntax: "SELECT name, salary, RANK() OVER (ORDER BY salary DESC) FROM employees;", description: "Rank rows (gaps for ties)" },
          { syntax: "SELECT name, salary, DENSE_RANK() OVER (ORDER BY salary DESC) FROM employees;", description: "Dense rank (no gaps)" },
          { syntax: "SELECT name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) FROM employees;", description: "Sequential row number" },
          { syntax: "SELECT name, dept, salary, AVG(salary) OVER (PARTITION BY dept) FROM employees;", description: "Aggregate within partition" },
        ],
      },
    ],
  },
  {
    slug: "typescript",
    title: "TypeScript Types",
    description: "Common TypeScript type patterns and utility types",
    icon: "💎",
    seoTitle: "TypeScript Cheat Sheet — Types, Utility Types & Patterns",
    seoDescription: "Complete TypeScript cheat sheet: basic types, interfaces, generics, utility types, type guards, and common patterns. Copy TypeScript code with one click.",
    sections: [
      {
        title: "Basic Types",
        items: [
          { syntax: "let name: string = 'Alice';", description: "String type" },
          { syntax: "let age: number = 30;", description: "Number type (int and float)" },
          { syntax: "let active: boolean = true;", description: "Boolean type" },
          { syntax: "let items: string[] = ['a', 'b'];", description: "Array of strings" },
          { syntax: "let tuple: [string, number] = ['a', 1];", description: "Tuple (fixed-length array)" },
          { syntax: "let value: any = 'whatever';", description: "Any type (opt out of checking)" },
          { syntax: "let id: string | number = 5;", description: "Union type (string or number)" },
          { syntax: "let dir: 'up' | 'down' = 'up';", description: "Literal type" },
          { syntax: "let notSure: unknown = 4;", description: "Unknown type (safer than any)" },
          { syntax: "function log(): void { console.log('hi'); }", description: "Void (no return value)" },
          { syntax: "let u: undefined = undefined;", description: "Undefined type" },
          { syntax: "let n: null = null;", description: "Null type" },
          { syntax: "function error(): never { throw new Error(); }", description: "Never type (no return)" },
        ],
      },
      {
        title: "Interfaces & Types",
        items: [
          { syntax: "interface User {\n  id: number;\n  name: string;\n  email?: string;\n}", description: "Interface with optional property" },
          { syntax: "interface Admin extends User {\n  role: 'admin';\n}", description: "Extend an interface" },
          { syntax: "type Point = { x: number; y: number; };", description: "Type alias for object shape" },
          { syntax: "type ID = string | number;", description: "Type alias for union" },
          { syntax: "type Callback = (data: string) => void;", description: "Function type alias" },
          { syntax: "interface User {\n  readonly id: number;\n  name: string;\n}", description: "Readonly property" },
          { syntax: "interface Dict { [key: string]: number; }", description: "Index signature (dictionary)" },
          { syntax: "type Rec = Record<string, number>;", description: "Same as above, using Record" },
        ],
      },
      {
        title: "Utility Types",
        items: [
          { syntax: "Partial<User>", description: "All properties optional" },
          { syntax: "Required<User>", description: "All properties required" },
          { syntax: "Readonly<User>", description: "All properties readonly" },
          { syntax: "Pick<User, 'id' | 'name'>", description: "Select specific properties" },
          { syntax: "Omit<User, 'password'>", description: "Exclude specific properties" },
          { syntax: "Record<string, User>", description: "Object with string keys → User values" },
          { syntax: "Exclude<'a' | 'b' | 'c', 'a'>", description: "Remove types from union → 'b' | 'c'" },
          { syntax: "Extract<'a' | 'b' | (() => void), Function>", description: "Extract matching types" },
          { syntax: "NonNullable<string | null | undefined>", description: "Remove null and undefined" },
          { syntax: "ReturnType<typeof myFn>", description: "Get return type of a function" },
          { syntax: "Parameters<typeof myFn>", description: "Get parameter types as tuple" },
          { syntax: "Awaited<Promise<User>>", description: "Unwrap promise type → User" },
        ],
      },
      {
        title: "Generics",
        items: [
          { syntax: "function first<T>(arr: T[]): T | undefined {\n  return arr[0];\n}", description: "Generic function" },
          { syntax: "interface ApiResponse<T> {\n  data: T;\n  status: number;\n}", description: "Generic interface" },
          { syntax: "type Container<T> = { value: T };", description: "Generic type alias" },
          { syntax: "function getProperty<T, K extends keyof T>(obj: T, key: K): T[K] {\n  return obj[key];\n}", description: "Generic with constraints (keyof)" },
        ],
      },
      {
        title: "Type Guards & Assertions",
        items: [
          { syntax: "if (typeof x === 'string') { x.toUpperCase(); }", description: "typeof type guard" },
          { syntax: "if ('id' in obj) { obj.id; }", description: "in operator type guard" },
          { syntax: "if (obj instanceof Date) { obj.getTime(); }", description: "instanceof type guard" },
          { syntax: "function isUser(obj: any): obj is User {\n  return obj && typeof obj.id === 'number';\n}", description: "Custom type predicate" },
          { syntax: "const el = document.getElementById('app') as HTMLDivElement;", description: "Type assertion (as)" },
          { syntax: "const val = expr!;", description: "Non-null assertion (use sparingly)" },
          { syntax: "const str = value as const;", description: "Const assertion (literal type)" },
          { syntax: "const arr = [1, 2, 3] as const;", description: "Readonly tuple assertion" },
        ],
      },
    ],
  },
  {
    slug: "npm",
    title: "NPM & Node.js",
    description: "Essential NPM, Node.js, and package.json commands",
    icon: "📦",
    seoTitle: "NPM Cheat Sheet — NPM & Node.js Commands Quick Reference",
    seoDescription: "Complete NPM cheat sheet: install, update, publish, scripts, npx, package.json fields, and Node.js CLI flags. Copy any command with one click.",
    sections: [
      {
        title: "Package Management",
        items: [
          { syntax: "npm init -y", description: "Create package.json with defaults" },
          { syntax: "npm install", description: "Install all dependencies" },
          { syntax: "npm install [pkg]", description: "Install and add to dependencies" },
          { syntax: "npm install [pkg]@[version]", description: "Install specific version" },
          { syntax: "npm install -D [pkg]", description: "Install as devDependency" },
          { syntax: "npm install -g [pkg]", description: "Install globally" },
          { syntax: "npm uninstall [pkg]", description: "Remove a package" },
          { syntax: "npm update [pkg]", description: "Update a package" },
          { syntax: "npm update", description: "Update all packages (respects semver)" },
          { syntax: "npm outdated", description: "Show outdated packages" },
          { syntax: "npm ls [pkg]", description: "List installed packages (tree)" },
          { syntax: "npm ls [pkg] --depth=0", description: "Top-level packages only" },
        ],
      },
      {
        title: "Version & Publish",
        items: [
          { syntax: "npm version major", description: "Bump major version (1.0.0 → 2.0.0)" },
          { syntax: "npm version minor", description: "Bump minor version (1.1.0 → 1.2.0)" },
          { syntax: "npm version patch", description: "Bump patch version (1.0.1 → 1.0.2)" },
          { syntax: "npm publish", description: "Publish package to registry" },
          { syntax: "npm publish --access public", description: "Publish scoped package as public" },
          { syntax: "npm login", description: "Log in to npm registry" },
        ],
      },
      {
        title: "Scripts & NPX",
        items: [
          { syntax: "npm run [script]", description: "Run a package.json script" },
          { syntax: "npm run build", description: "Common build script" },
          { syntax: "npm start", description: "Shorthand for npm run start" },
          { syntax: "npm test", description: "Shorthand for npm run test" },
          { syntax: "npx [command]", description: "Run a package without installing" },
          { syntax: "npx create-next-app@latest", description: "Scaffold Next.js app (example)" },
          { syntax: "npx tsc --init", description: "Initialize TypeScript config" },
          { syntax: "npx eslint .", description: "Run ESLint without installing" },
        ],
      },
      {
        title: "Cache & Config",
        items: [
          { syntax: "npm cache clean --force", description: "Force clean npm cache" },
          { syntax: "npm config list", description: "Show npm config" },
          { syntax: "npm config set registry [url]", description: "Change registry" },
          { syntax: "npm config set proxy [url]", description: "Set proxy" },
          { syntax: "npm config delete proxy", description: "Remove proxy setting" },
        ],
      },
      {
        title: "package.json Fields",
        items: [
          { syntax: "\"files\": [\"dist\", \"README.md\"]", description: "Files to include when publishing" },
          { syntax: "\"main\": \"./dist/index.js\"", description: "Entry point for CommonJS" },
          { syntax: "\"module\": \"./dist/index.mjs\"", description: "Entry point for ESM" },
          { syntax: "\"types\": \"./dist/index.d.ts\"", description: "TypeScript declaration entry" },
          { syntax: "\"exports\": { \".\": { \"import\": \"./dist/index.mjs\", \"require\": \"./dist/index.js\" } }", description: "Modern exports map" },
          { syntax: "\"engines\": { \"node\": \">=18\" }", description: "Required Node.js version" },
          { syntax: "\"private\": true", description: "Prevent accidental publish" },
        ],
      },
    ],
  },
];

export function getCheatSheet(slug: string): CheatSheet | undefined {
  return cheatsheets.find((s) => s.slug === slug);
}

export function getAllCheatSheetSlugs(): string[] {
  return cheatsheets.map((s) => s.slug);
}
